sudo: false

language: haskell
ghc:
  - "8.6.4"

script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test
  - cabal configure --enable-tests --enable-library-coverage
  - cabal build
  - cabal test --show-details=always

after_script:
  - cabal install hpc-coveralls
  - cabal exec hpc-coveralls --coverage-mode=StrictlyFullLines --exclude-dir=test test-all