name:                lazyboy
version:             0.2.2.1
github:              "ix/lazyboy"
license:             BSD3
author:              "Rose"
maintainer:          "rose@lain.org.uk"
copyright:           "2019 Rose"
category:            DSL, Compiler
synopsis:            An EDSL for programming the Game Boy.

extra-source-files:
- README.md
- ChangeLog.md

# templates
data-files: templates/*.mustache

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: An EDSL for programming the Nintendo Game Boy. <https://github.com/ix/lazyboy#readme>

dependencies:
 - aeson
 - base 
 - hspec 
 - microstache 
 - text
 - transformers
 - matrix 

library:
  source-dirs: src

tests:
  lazyboy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lazyboy 


ghc-options: ["-optP-Wno-nonportable-include-path"]
